version: '3.8'

services:
    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: pln_backend
        ports:
            - "3201:8000"
        volumes:
            - .:/app
        environment:
            APP_ENV: ${APP_ENV}
            APP_DEBUG: ${APP_DEBUG}
            LOG_CHANNEL: ${LOG_CHANNEL}

            # MAIN DB
            DB_CONNECTION: ${DB_CONNECTION}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}

            # TRANSACTION DB
            SECOND_DB_CONNECTION: ${SECOND_DB_CONNECTION}
            SECOND_DB_HOST: ${SECOND_DB_HOST}
            SECOND_DB_PORT: ${SECOND_DB_PORT}
            SECOND_DB_DATABASE: ${SECOND_DB_DATABASE}
            SECOND_DB_USERNAME: ${SECOND_DB_USERNAME}
            SECOND_DB_PASSWORD: ${SECOND_DB_PASSWORD}

            # DOCUMENT DB
            DOCUMENT_DB_CONNECTION: ${DOCUMENT_DB_CONNECTION}
            DOCUMENT_DB_HOST: ${DOCUMENT_DB_HOST}
            DOCUMENT_DB_PORT: ${DOCUMENT_DB_PORT}
            DOCUMENT_DB_DATABASE: ${DOCUMENT_DB_DATABASE}
            DOCUMENT_DB_USERNAME: ${DOCUMENT_DB_USERNAME}
            DOCUMENT_DB_PASSWORD: ${DOCUMENT_DB_PASSWORD}

            # min io
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
            AWS_BUCKET: ${AWS_BUCKET}
            AWS_ENDPOINT: ${AWS_ENDPOINT}
            AWS_USE_PATH_STYLE_ENDPOINT: ${AWS_USE_PATH_STYLE_ENDPOINT}

        depends_on:
            - mysql
            - minio
        networks:
            - laravel_net
        extra_hosts:
            - "host.docker.internal:host-gateway"

    mysql:
        image: mysql:8
        container_name: mysql_container
        restart: unless-stopped
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel_net

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - "8080:80"
        networks:
            - laravel_net

    minio:
        image: minio/minio
        container_name: minio
        ports:
            - "9000:9000" # API
            - "9001:9001" # Web UI
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        command: server /data --console-address ":9001"
        volumes:
            - ./minio-data:/data
        networks:
            - laravel_net
            - bridge_public

volumes:
    mysql_data:


networks:
    laravel_net:
    bridge_public:
        driver: bridge
