FROM php:8.2-cli-alpine

RUN apk add --no-cache \
    bash git unzip libzip-dev libpng-dev oniguruma-dev libxml2-dev curl \
    && docker-php-ext-install pdo pdo_mysql zip mbstring xml

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /app

CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
