version: '3.8'

services:
    laravel:
        build:
            context: .
            dockerfile: Dockerfile # Production Dockerfile
        container_name: pln_backend
        ports:
            - "3201:8000"
        environment:
            APP_ENV: ${APP_ENV}
            APP_DEBUG: ${APP_DEBUG}
            LOG_CHANNEL: ${LOG_CHANNEL}

        depends_on:
            - mysql
            - minio
        networks:
            - laravel_net
        extra_hosts:
            - "host.docker.internal:host-gateway"
        mem_limit: 512m
        restart: unless-stopped

    mysql:
        image: mysql:8
        container_name: mysql_container
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel_net
        mem_limit: 1500m
        restart: unless-stopped

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - "8080:80"
        networks:
            - laravel_net
        mem_limit: 256m
        restart: unless-stopped

    minio:
        image: minio/minio:RELEASE.2023-07-21T21-12-44Z
        container_name: minio
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        command: server /data --console-address ":9001"
        volumes:
            - ./minio-data:/data
        networks:
            - laravel_net
            - bridge_public
        mem_limit: 512m
        restart: unless-stopped

volumes:
    mysql_data:


networks:
    laravel_net:
    bridge_public:
        driver: bridge
